### ISSUE TITLE
scroll file with onscreen keyboard

### ISSUE THREAD

**Issue by 0rovan** [milikhin/seabass#12]
If onscreen keyboard is enabled Seabass does not view bottom lines of (not tiny)files becase keyboard is in the way. Fix might be adding padding to the bottom of the file if keyboard is enabled. Placeholder for OSK keyboard does NOT cause same issue and behaves how I would expect normal keyboard to behave also.

**Comment by milikhin** [comment]
Thank you for the feedback.

It is a [bug](https://bugs.launchpad.net/cordova-ubuntu/+bug/1419979) in Cordova framework for Ubuntu (which is used as a platform for Seabass): the application is not resized when OSK is opened.

Cordova for Ubuntu is abandoned for a while now, so this bug among others wasn't fixed for years. In fact, that's why OSK placeholder was added to the app.

I'm thinking about switching away from Cordova and using latest Ubuntu's components, but not until when it is clear what is the future of Ubuntu's native SDK and Cordova/HTML5 SDK within Ubports project.

**Comment by milikhin** [comment]
Fixed in v0.4.7 built with patched Cordova
