### ISSUE TITLE
File tree width not correct

### ISSUE THREAD

**Issue by moritz-weber** [milikhin/seabass#9]
Pixel values of the file tree width don't match the actual width. At least on the Nexus 7.
The screenshots show a 400px and 150px file tree.

![screenshot20160902_224333585](https://cloud.githubusercontent.com/assets/17176771/18218070/ac94da2a-7160-11e6-802c-507dbf5dcd85.png)
![screenshot20160902_224355979](https://cloud.githubusercontent.com/assets/17176771/18218074/af7e08ce-7160-11e6-89c3-8ac2d0a824fa.png)

**Comment by milikhin** [comment]
Ah, that's because Seabass uses [CSS definition of pixel unit](https://www.w3.org/TR/CSS21/syndata.html#length-units) according to which **1px = 1/96in** and "px" is not actually related to physical screen pixels. It helps scaling UI properly on devices with different pixel densities.

Anyway, thank you! I think, i might need to explicitly note this fact somewhere on the settings page.
